spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/OrdersDb
        username: root
        password: roottroller
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
