spring:
  profiles:
    active: 
    - dev
  datasource:
    hikari:
  jpa:
    properties:
      hibernate.jdbc.batch_size: 2500
      hibernate.order_inserts: true
      hibernate.enable_lazy_load_no_trans: true 
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
